### ISSUE TITLE
Regression: v1.3.7 fails to run ("could not determine executable to run")

### ISSUE THREAD

**Issue by cmd-johnson** [sabinadams/aurora#126]
**Describe the bug**
After updating to v1.3.7, aurora fails to run with the following error:
```
npm ERR! could not determine executable to run
```

Running the previous version (via `npx prisma-aurora@1.3.6`) works as expected.

The same error also occurs when running aurora via `npx prisma-aurora` or `yarn dlx prisma-aurora`. Both `npx prisma-aurora@1.3.6` and `yarn dlx prisma-aurora@1.3.6` work just fine.

I'm guessing this is because the `"bin"` field was removed from the `package.json` file in be3b0d2b3f854fb747ee54bb7c005a7d7d4677a4.

**To Reproduce**
1. Create a new, empty `npm` project (e.g. via `npm init`)
2. Run `npm i --save-dev prisma-aurora@1.3.7`
3. Run `npm exec aurora` (or add a `start` script to the `package.json` (`"scripts": { "start": "aurora" }`) and run `npm start`)
4. The above error is shown

After reverting to v1.3.6 using `npm i --save-dev prisma-aurora@1.3.6`, the above commands run just fine (well, the actual runs fail, but that's because there's no aurora config available in this example).

**Expected behavior**
Running `npm exec aurora` works like normal

**Desktop (please complete the following information):**
 - OS: Linux (Manjaro)
 - Node: v17.8.0
 - npm: 8.5.5

**Comment by sabinadams** [comment]
Just pushed an update `v1.3.9` that should fix this issue.

**Comment by cmd-johnson** [comment]
Thank you for the quick fix! :heart:
