### ISSUE TITLE
@db type attributes resulting in a compilation error

### ISSUE THREAD

**Issue by uvalus** [sabinadams/aurora#34]
**Describe the bug**
Putting together a schema and looking to use the @db type annotations results in a compilation error with the message about InvalidNativeType. 

This is the case regardless of the @db type annotation used (VarChar, DateTime etc..).

Is this expected behaviour which is on a roadmap to implement or is it a bug that needs addressing ?

**To Reproduce**

Have a file named connection.prisma as follows:

````
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
  binaryTargets   = ["native", "rhel-openssl-1.0.x", "linux-arm64-openssl-1.0.x"]
}

datasource db {
  provider             = "mysql"
  url                  = env("DATABASE_STAGING_URL")
  shadowDatabaseUrl    = env("DATABASE_SHADOW_URL")
  referentialIntegrity = "prisma"
}
````

Have a model defined as this in a file named (currency.prisma):

````
model Currency {
  id              Int               @id @default(autoincrement())
  code            String            @unique
  description     String
  createdAt       DateTime          @default(now()) @db.DateTime(6)
  updatedAt       DateTime          @updatedAt  @db.DateTime(6)
}
````

And an aurora.config.json file which looks like: 

```` 
{
  "files": [
    "./connection.prisma",
    "./currency.prisma"
  ],
  "output": "./schema.prisma"
}
````
Run the `aurora` command

**Expected behavior**
A schema file is created which contains the native type annotations

**Screenshots**
![image](https://user-images.githubusercontent.com/70891154/152509541-89f784e7-5db7-49b2-884a-300cc3365851.png)

**Desktop (please complete the following information):**
 - macOS 12.1
 - Node 14.18.2
 - Prisma: 3.8.1

**Comment by sabinadams** [comment]
Related to #13
Caused by the same issue

**Comment by uvalus** [comment]
Hi, I've just tried this again on the latest version (1.3.2) and am still getting the same error.
