### ISSUE TITLE
Running aurora

### ISSUE THREAD

**Issue by Gouet** [sabinadams/aurora#4]
Hi, 

Thanks for this new service that can help a lot !

I don't know how to run aurora, can you please describe more how to run it after download the package ?

Thanks

**Comment by Gouet** [comment]
Ok I found the solution with :
1. `npm install -g prisma-aurora`
2. `aurora`

**Comment by sabinadams** [comment]
@Gouet Thanks for the feedback! I plan to revise the README so it is a bit more clear and descriptive of the options available. I'm marking this with the appropriate labels so I'll be sure to get to it. 

Thanks!
