### ISSUE TITLE
Missing one-letter enum values

### ISSUE THREAD

**Issue by babyradJiri** [sabinadams/aurora#54]
**Describe the bug**
Missing one-letter enum values after running aurora.

**To Reproduce**
1. With the following enum:
![image](https://user-images.githubusercontent.com/37667133/153733413-6b58d82a-4606-40b7-ae24-25047e1d898b.png)

2. Running aurora will result in:
![image](https://user-images.githubusercontent.com/37667133/153733423-c2aaad1f-8524-48e0-aa96-cca5cb23b851.png)

**Expected behavior**
Enum should contain both values

**Comment by sabinadams** [comment]
Thanks for catching this, I'll take a look!
